/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbol.binario.listaligada.busqueda.avl.ejemplos.diccionario;

import arbol.binario.listaligada.busqueda.avl.NodoAVL;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaBuscarPalabra extends javax.swing.JFrame {

    public Diccionario diccionario;
    public Palabra pala;
    private int option;
    private boolean modeEdition;
    

    public int getOption() {
        return option;
    }

    public void setOption(int option) {
        this.option = option;
    }
    

    /**
     * Creates new form NewJFrame
     */
    public VentanaBuscarPalabra() {
        initComponents();
        this.modeEdition=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Significado1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResultado1 = new javax.swing.JTextArea();
        Panel_Resultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Resultado = new javax.swing.JTextArea();
        Btn_Cargar = new javax.swing.JButton();
        Panel_Antonimos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea_Antonimos = new javax.swing.JTextArea();
        Lb_CantidadAntonimos = new javax.swing.JLabel();
        LabelNumAntonimos = new javax.swing.JLabel();
        Panel_Sinonimos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextArea_Sinonimos = new javax.swing.JTextArea();
        Lb_CantidadSinonimos = new javax.swing.JLabel();
        LabelNumSinonimos = new javax.swing.JLabel();
        Btn_BuscarPalabra = new javax.swing.JButton();
        Btn_AgregarPalabra = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        TextArea_Palabra = new javax.swing.JTextField();
        PanelSigni = new javax.swing.JPanel();
        Lb_CantidadPalabras = new javax.swing.JLabel();
        LabelNumPalabras = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextArea_Significado = new javax.swing.JTextArea();
        Btn_ModificarPalabra = new javax.swing.JButton();
        Btn_GuardarPalabra = new javax.swing.JButton();
        Btn_Exportar = new javax.swing.JButton();

        Panel_Significado1.setBorder(javax.swing.BorderFactory.createTitledBorder("Significado"));
        Panel_Significado1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextAreaResultado1.setEditable(false);
        jTextAreaResultado1.setColumns(20);
        jTextAreaResultado1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResultado1);

        javax.swing.GroupLayout Panel_Significado1Layout = new javax.swing.GroupLayout(Panel_Significado1);
        Panel_Significado1.setLayout(Panel_Significado1Layout);
        Panel_Significado1Layout.setHorizontalGroup(
            Panel_Significado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        Panel_Significado1Layout.setVerticalGroup(
            Panel_Significado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Significado1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Resultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        Panel_Resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TextArea_Resultado.setEditable(false);
        TextArea_Resultado.setColumns(20);
        TextArea_Resultado.setRows(5);
        jScrollPane1.setViewportView(TextArea_Resultado);
        TextArea_Resultado.getAccessibleContext().setAccessibleName("Resultado");
        TextArea_Resultado.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout Panel_ResultadoLayout = new javax.swing.GroupLayout(Panel_Resultado);
        Panel_Resultado.setLayout(Panel_ResultadoLayout);
        Panel_ResultadoLayout.setHorizontalGroup(
            Panel_ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ResultadoLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        Panel_ResultadoLayout.setVerticalGroup(
            Panel_ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Btn_Cargar.setText("Cargar Diccionario");
        Btn_Cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CargarMouseClicked(evt);
            }
        });
        Btn_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CargarActionPerformed(evt);
            }
        });

        Panel_Antonimos.setBorder(javax.swing.BorderFactory.createTitledBorder("Antonimos"));
        Panel_Antonimos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TextArea_Antonimos.setEditable(false);
        TextArea_Antonimos.setColumns(20);
        TextArea_Antonimos.setRows(5);
        jScrollPane3.setViewportView(TextArea_Antonimos);

        Lb_CantidadAntonimos.setText("Cantidad de palabras en el diccionario: ");

        LabelNumAntonimos.setText("0");

        javax.swing.GroupLayout Panel_AntonimosLayout = new javax.swing.GroupLayout(Panel_Antonimos);
        Panel_Antonimos.setLayout(Panel_AntonimosLayout);
        Panel_AntonimosLayout.setHorizontalGroup(
            Panel_AntonimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AntonimosLayout.createSequentialGroup()
                .addGroup(Panel_AntonimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(Panel_AntonimosLayout.createSequentialGroup()
                        .addComponent(Lb_CantidadAntonimos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNumAntonimos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_AntonimosLayout.setVerticalGroup(
            Panel_AntonimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AntonimosLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Panel_AntonimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_CantidadAntonimos)
                    .addComponent(LabelNumAntonimos)))
        );

        Panel_Sinonimos.setBorder(javax.swing.BorderFactory.createTitledBorder("Sinonimos"));
        Panel_Sinonimos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TextArea_Sinonimos.setEditable(false);
        TextArea_Sinonimos.setColumns(20);
        TextArea_Sinonimos.setRows(5);
        jScrollPane4.setViewportView(TextArea_Sinonimos);

        Lb_CantidadSinonimos.setText("Cantidad de palabras en el diccionario: ");

        LabelNumSinonimos.setText("0");

        javax.swing.GroupLayout Panel_SinonimosLayout = new javax.swing.GroupLayout(Panel_Sinonimos);
        Panel_Sinonimos.setLayout(Panel_SinonimosLayout);
        Panel_SinonimosLayout.setHorizontalGroup(
            Panel_SinonimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SinonimosLayout.createSequentialGroup()
                .addGroup(Panel_SinonimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(Panel_SinonimosLayout.createSequentialGroup()
                        .addComponent(Lb_CantidadSinonimos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNumSinonimos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_SinonimosLayout.setVerticalGroup(
            Panel_SinonimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SinonimosLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_SinonimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_CantidadSinonimos)
                    .addComponent(LabelNumSinonimos)))
        );

        Btn_BuscarPalabra.setText("Buscar ");
        Btn_BuscarPalabra.setToolTipText("Buscar la palabra en el diccionario");
        Btn_BuscarPalabra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_BuscarPalabraMouseClicked(evt);
            }
        });
        Btn_BuscarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarPalabraActionPerformed(evt);
            }
        });

        Btn_AgregarPalabra.setText("Agregar ");
        Btn_AgregarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarPalabraActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Palabra"));

        TextArea_Palabra.setToolTipText("Ingrese la palabra a buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextArea_Palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextArea_Palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelSigni.setBorder(javax.swing.BorderFactory.createTitledBorder("Significado"));

        Lb_CantidadPalabras.setText("Cantidad de palabras en el diccionario: ");

        LabelNumPalabras.setText("0");

        TextArea_Significado.setEditable(false);
        TextArea_Significado.setColumns(20);
        TextArea_Significado.setRows(5);
        jScrollPane5.setViewportView(TextArea_Significado);
        TextArea_Significado.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout PanelSigniLayout = new javax.swing.GroupLayout(PanelSigni);
        PanelSigni.setLayout(PanelSigniLayout);
        PanelSigniLayout.setHorizontalGroup(
            PanelSigniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSigniLayout.createSequentialGroup()
                .addComponent(Lb_CantidadPalabras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNumPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(PanelSigniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSigniLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane5)
                    .addGap(3, 3, 3)))
        );
        PanelSigniLayout.setVerticalGroup(
            PanelSigniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSigniLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(PanelSigniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_CantidadPalabras)
                    .addComponent(LabelNumPalabras))
                .addContainerGap())
            .addGroup(PanelSigniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSigniLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addGap(34, 34, 34)))
        );

        Btn_ModificarPalabra.setText("Modificar ");
        Btn_ModificarPalabra.setToolTipText("");
        Btn_ModificarPalabra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_ModificarPalabraMouseClicked(evt);
            }
        });
        Btn_ModificarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarPalabraActionPerformed(evt);
            }
        });

        Btn_GuardarPalabra.setText("Guardar");
        Btn_GuardarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarPalabraActionPerformed(evt);
            }
        });

        Btn_Exportar.setText("Exportar Diccionario");
        Btn_Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Sinonimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Btn_BuscarPalabra)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_AgregarPalabra)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_ModificarPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_GuardarPalabra)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Panel_Antonimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelSigni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Panel_Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Cargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Exportar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Cargar)
                    .addComponent(Btn_Exportar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSigni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Panel_Sinonimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Antonimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_BuscarPalabra)
                    .addComponent(Btn_AgregarPalabra)
                    .addComponent(Btn_ModificarPalabra)
                    .addComponent(Btn_GuardarPalabra))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void PedirDatos_llenarCampo(){
        
        if(TextArea_Significado.getText().equals("")) 
            TextArea_Significado.setText("Indique el significado de la palabra");
        if(TextArea_Sinonimos.getText().equals("")) 
            TextArea_Sinonimos.setText("Indique el o los sinonimos de la palabra");
        if(TextArea_Antonimos.getText().equals("")) 
        TextArea_Antonimos.setText("Indique el o los antonimos de la palabra");
    }
    public void LimpiarCampo(){
        TextArea_Significado.setText("");
        TextArea_Sinonimos.setText("");
        TextArea_Antonimos.setText("");
        TextArea_Resultado.setText("");
        TextArea_Palabra.setText("");
    }

    
   /* public void LlenarCampo_DatosPalabra(NodoAVL pal){
        TextArea_Significado.setText((String) pal.getDato());
    }*/
    
    public void EditarCampoPalabra(boolean opcion){
        TextArea_Significado.setEditable(opcion);
        TextArea_Sinonimos.setEditable(opcion);
        TextArea_Antonimos.setEditable(opcion);
    }
    
    public void ModificarDatosPalabra(Palabra actual, String significado, String sinonimo, String antonimo){
    Palabra palabraNueva = new Palabra(actual.getCadena(), significado,sinonimo, antonimo ); 
    diccionario.ModificarPalabra(actual, palabraNueva);
    }

    
    public void ImprimirDatosConsola(Palabra pa){
        System.out.println(pa.getCadena());
        System.out.println(pa.getSignificado());
        System.out.println(pa.getSinonimo());
        System.out.println(pa.getAntonimo()+"\n");
    }
    public void LlenarCampo_DatosPalabra(Palabra dato){
        if(dato.getSignificado() != null)TextArea_Significado.setText(dato.getSignificado());
        if(dato.getSinonimo() != null)TextArea_Sinonimos.setText(dato.getSinonimo());
        if(dato.getAntonimo()!= null )TextArea_Antonimos.setText(dato.getAntonimo());
    }    
    
    public boolean CamposEstanVacios(){
        return "".equals(TextArea_Significado.getText())|| "".equals(TextArea_Sinonimos.getText())||
                "".equals(TextArea_Antonimos.getText());
    }
    
    
    private void Btn_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_CargarActionPerformed

    private void Btn_CargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CargarMouseClicked
        try {
            diccionario = new Diccionario(TextArea_Resultado, TextArea_Significado, TextArea_Sinonimos, TextArea_Antonimos);
            if (diccionario != null) {
                LabelNumPalabras.setText(diccionario.getCantidad() + "");
            }

        } catch (Exception ex) {
            Logger.getLogger(VentanaBuscarPalabra.class.getName()).log(Level.SEVERE, null, ex);
        }
        Btn_Cargar.setEnabled(false);
        Btn_AgregarPalabra.setEnabled(false);
        Btn_ModificarPalabra.setEnabled(false);
        Btn_GuardarPalabra.setEnabled(false);
    }//GEN-LAST:event_Btn_CargarMouseClicked


    
    private void Btn_BuscarPalabraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BuscarPalabraMouseClicked

    }//GEN-LAST:event_Btn_BuscarPalabraMouseClicked

   
    private void Btn_BuscarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarPalabraActionPerformed
        String cadena = TextArea_Palabra.getText();
        String significado = TextArea_Significado.getText();
        String sinonimos = TextArea_Sinonimos.getText();
        String antonimos = TextArea_Antonimos.getText();
        Palabra pala = new Palabra(cadena, significado, sinonimos, antonimos);
        Palabra miDato=diccionario.BuscarPalabra(pala);       
        
        
       if(!diccionario.isBandera()){
            PedirDatos_llenarCampo();
            EditarCampoPalabra(true);            
            Btn_AgregarPalabra.setEnabled(true);
       }else{
           System.out.println(miDato);
           LlenarCampo_DatosPalabra(miDato);
           LabelNumPalabras.setText(diccionario.getCantidad() + "");
            if (CamposEstanVacios()){
                PedirDatos_llenarCampo();
                EditarCampoPalabra(true);
                Btn_GuardarPalabra.setEnabled(true);
            }else{
                Btn_ModificarPalabra.setEnabled(true);
            }    
       }
    }//GEN-LAST:event_Btn_BuscarPalabraActionPerformed

    
    
    private void Btn_AgregarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarPalabraActionPerformed
        String cadena = TextArea_Palabra.getText();
        String significado = TextArea_Significado.getText();
        String sinonimos = TextArea_Sinonimos.getText();
        String antonimos = TextArea_Antonimos.getText();
        Palabra palab=new Palabra(cadena, significado, sinonimos, antonimos);
        try {
            diccionario.InsertarPalabra(palab);
            LabelNumPalabras.setText(diccionario.getCantidad() + "");

        } catch (Exception ex) {
            Logger.getLogger(VentanaBuscarPalabra.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImprimirDatosConsola(palab);
        EditarCampoPalabra(false);
        LimpiarCampo();
        Btn_AgregarPalabra.setEnabled(false);       
    }//GEN-LAST:event_Btn_AgregarPalabraActionPerformed

    private void Btn_ModificarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarPalabraActionPerformed
        
            String cadena = TextArea_Palabra.getText();
            String significado = TextArea_Significado.getText();
            String sinonimos = TextArea_Sinonimos.getText();
            String antonimos = TextArea_Antonimos.getText();
            Palabra palab=new Palabra(cadena, significado, sinonimos, antonimos);
            ModificarDatosPalabra(palab, significado, sinonimos, antonimos);
            ImprimirDatosConsola(palab);
        
    }//GEN-LAST:event_Btn_ModificarPalabraActionPerformed

    
    private void Btn_ModificarPalabraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ModificarPalabraMouseClicked
        if (!modeEdition){
           JOptionPane.showConfirmDialog(null,"¿Desea modificar la palabra?");
            if (JOptionPane.OK_OPTION == 0){
                modeEdition=true;
                EditarCampoPalabra(true);
                Btn_ModificarPalabra.setText("Cancelar");
                Btn_GuardarPalabra.setEnabled(true);
                LabelNumPalabras.setText(diccionario.getCantidad() + "");
            }
    
        }else{ modeEdition=false;
                EditarCampoPalabra(false);
                Btn_ModificarPalabra.setText("Modificar Palabra");
                Btn_GuardarPalabra.setEnabled(false);
                
        }
    }//GEN-LAST:event_Btn_ModificarPalabraMouseClicked
    
    private void Btn_GuardarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarPalabraActionPerformed
        String cadena = TextArea_Palabra.getText();
        String significado = TextArea_Significado.getText();
        String sinonimos = TextArea_Sinonimos.getText();
        String antonimos = TextArea_Antonimos.getText();

        Palabra palab = new Palabra(cadena, significado, sinonimos, antonimos);

        ModificarDatosPalabra(palab, significado, sinonimos, antonimos);
        ImprimirDatosConsola(palab);
        LabelNumPalabras.setText(diccionario.getCantidad() + "");
        EditarCampoPalabra(false);
        LimpiarCampo();
        Btn_GuardarPalabra.setEnabled(false);
        Btn_ModificarPalabra.setEnabled(false);
    }//GEN-LAST:event_Btn_GuardarPalabraActionPerformed

    private void Btn_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ExportarActionPerformed
        try {
            diccionario.root.generarArchivo();
        } catch (IOException ex) {
            Logger.getLogger(VentanaBuscarPalabra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_ExportarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                new VentanaBuscarPalabra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AgregarPalabra;
    private javax.swing.JButton Btn_BuscarPalabra;
    private javax.swing.JButton Btn_Cargar;
    private javax.swing.JButton Btn_Exportar;
    private javax.swing.JButton Btn_GuardarPalabra;
    private javax.swing.JButton Btn_ModificarPalabra;
    private javax.swing.JLabel LabelNumAntonimos;
    private javax.swing.JLabel LabelNumPalabras;
    private javax.swing.JLabel LabelNumSinonimos;
    private javax.swing.JLabel Lb_CantidadAntonimos;
    private javax.swing.JLabel Lb_CantidadPalabras;
    private javax.swing.JLabel Lb_CantidadSinonimos;
    private javax.swing.JPanel PanelSigni;
    private javax.swing.JPanel Panel_Antonimos;
    private javax.swing.JPanel Panel_Resultado;
    private javax.swing.JPanel Panel_Significado1;
    private javax.swing.JPanel Panel_Sinonimos;
    private javax.swing.JTextArea TextArea_Antonimos;
    private javax.swing.JTextField TextArea_Palabra;
    private javax.swing.JTextArea TextArea_Resultado;
    private javax.swing.JTextArea TextArea_Significado;
    private javax.swing.JTextArea TextArea_Sinonimos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaResultado1;
    // End of variables declaration//GEN-END:variables
}
